INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (14, 12, 'Eius veniam aut.', 16, 136.03, 46.35, 'eius-veniam-aut', 6, 0, 8, 'Enim enim at tempore dolores repellendus quasi. Quisquam optio illo molestiae praesentium. Aut at suscipit distinctio ipsa. Deserunt temporibus minima laudantium occaecati sint et esse.
Voluptatem possimus natus sequi consectetur officia sed dolor quia. Illo blanditiis neque eaque perferendis aut. Aut magnam facilis est a sit perspiciatis non facere. Atque rerum quam porro voluptatem.', 112.77, 306.16, 50.92, 325.41, 473.65, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (4, 1, 'Laborum est sed.', 3, 136.11, 38.09, 'laborum-est-sed', 4, 0, 47, 'Dolorem necessitatibus et aperiam dolorum repudiandae accusantium quia cum. Quas explicabo iusto dolores tempore minima perspiciatis temporibus ea. Odit illum laboriosam aut non similique incidunt. Error doloremque architecto voluptatem molestiae.
Aliquam possimus nisi corporis ut nihil dolor consectetur praesentium. Sed est quos nulla facilis. Incidunt saepe quia rerum libero qui. Repellat aut voluptatem ab dolores optio.', 417.16, 361.83, 349.08, 333.63, 414.64, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (11, 13, 'Eos eos vitae.', 19, 166.37, 11.64, 'eos-eos-vitae', 14, 1, 2, 'Saepe commodi temporibus ullam laudantium autem nobis praesentium. Dolorem et neque error repellat est omnis sapiente unde. Sed dicta eum doloremque iusto mollitia. Repudiandae et magni et eius in.
Pariatur temporibus quo deserunt non architecto maxime ut velit. Magni expedita ab numquam est quas ab quas. Natus amet nisi eveniet dolores.', 100.53, 424.09, 470.1, 168.01, 426.97, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (11, 10, 'Totam nisi labore laudantium vel.', 20, 167.56, 3.22, 'totam-nisi-labore-laudantium-vel', 8, 0, 12, 'Sint quaerat harum ad tempore accusamus natus. Vel ex culpa architecto.
Praesentium quo nesciunt dolores quia quo unde sit. Rerum deserunt fugiat corrupti eveniet in voluptas et.
Porro porro quod alias repellendus expedita. Voluptatem aut sint consequuntur.
Asperiores dolor officia officia ipsa. Enim quibusdam consectetur corrupti id. Suscipit eaque eligendi esse distinctio voluptatum. Qui nulla labore tempora rerum quae rem.', 33.84, 59.35, 321.78, 112.75, 477.4, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (12, 3, 'Officia ipsum tenetur odit.', 13, 105.69, 9.72, 'officia-ipsum-tenetur-odit', 8, 1, 46, 'Nam similique a officia qui numquam et. Dolores velit dolorem illo rerum quia est fugiat praesentium. Qui est accusamus repellat exercitationem quam commodi qui et. Laborum ratione perferendis maiores.
Praesentium ut delectus officiis ratione aut. Totam accusantium harum sapiente tenetur at est est. Dolores velit iusto tenetur earum voluptas. Sequi exercitationem in ad ipsam modi.
Atque autem sunt velit quibusdam accusantium quis. Ut aut quis iure facere.', 129.58, 383.66, 34.02, 187.06, 199.83, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (1, 9, 'Nobis officia quasi vel.', 9, 131.44, 1.21, 'nobis-officia-quasi-vel', 9, 1, 24, 'Inventore sapiente distinctio nihil. Est recusandae labore sit nulla pariatur. Tempore voluptas soluta quia voluptatem. Voluptas expedita ut expedita enim voluptatem cupiditate dolorem.
Exercitationem ipsam qui numquam id nam et. Voluptate nam magnam sequi porro vel. Sit quis odio corrupti quo enim. Ea aut ut quod tempora et.
Natus maiores vel est quibusdam est suscipit. Deleniti cum atque voluptatem minus adipisci sed voluptatem. Sed temporibus quas minima eos commodi.', 171.06, 353.62, 243.84, 52.17, 346.36, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (10, 3, 'Odio modi odit quo.', 13, 60.22, 40.58, 'odio-modi-odit-quo', 1, 0, 36, 'Incidunt sunt commodi architecto a incidunt. Est hic commodi eum ut. Consequatur nulla et animi et.
Beatae est tempora accusamus unde. Neque exercitationem ut esse voluptates inventore molestias repudiandae. Tempora qui quod omnis dolorem iste. Ullam repudiandae aut aut ut at totam commodi. Sit saepe nihil qui sit doloribus animi.', 89.8, 189.81, 466.49, 98.05, 341.7, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (7, 3, 'Temporibus itaque blanditiis quam.', 5, 55.34, 9.03, 'temporibus-itaque-blanditiis-quam', 8, 0, 4, 'Perspiciatis quos ullam saepe repellat. Voluptatem sint temporibus ut expedita voluptatibus doloremque. Libero reiciendis doloribus magnam. Optio qui non eos neque repellat occaecati velit.
Natus quia laborum vitae enim amet similique excepturi. Excepturi quod mollitia aut. Velit enim error iste.
Est omnis similique quia. Aut reiciendis et neque sit officiis odio. Et explicabo nemo non voluptates et perspiciatis eveniet.', 302.36, 471.36, 124.84, 366.54, 263.66, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (9, 3, 'Ipsam quibusdam iste aut.', 4, 118.15, 37.27, 'ipsam-quibusdam-iste-aut', 13, 0, 27, 'Eligendi cum asperiores ut accusamus dignissimos quia voluptatem. Vel velit recusandae eligendi eveniet reprehenderit deserunt. Aspernatur voluptatem corporis laboriosam esse aliquam. Deserunt impedit sequi voluptas quae.
Veniam et nesciunt sed quos. Consequatur dolor voluptas quae ipsum nobis quo repudiandae. Eos similique ut est voluptas iure amet autem. In optio voluptas doloremque eius et ut. Et alias ut eaque aspernatur et adipisci est.', 299.9, 312.02, 242.62, 17.78, 273.35, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (14, 6, 'Et et.', 14, 58.94, 26.36, 'et-et', 3, 0, 1, 'Ipsam fuga excepturi quis sint reiciendis. Minus consequatur odio nihil totam ipsa nostrum alias. Autem magnam incidunt dolor autem voluptas quasi quia.
Distinctio officia officia in vero. Consequatur eum eaque beatae saepe quibusdam quisquam. Soluta modi mollitia dicta dolorem vero. Dolore iste sed quidem voluptas voluptatem excepturi. Consequatur non beatae corporis voluptatibus unde quisquam.', 91.5, 198.58, 167.2, 396.94, 272.45, 1, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (15, 5, 'Produto de exemplo', 1, 27.90, 25.90, 'produto-de-exemplo', 1, 1, 10, 'sdasdsdf 
sd fsadf asd
asd fasf sda rn tyb 
ty nmyum rsgw fgnyr
', 100, 100, 100, 100, 100, 0, '2017-02-21 12:48:41', '2017-02-21 12:48:41');
INSERT INTO popmartin.products (store_id, category_id, name, quantity, price, price_out_discount, slug, deadline, free_shipping, minimum_stock, details, length_cm, width_cm, height_cm, weight_gr, diameter_cm, active, created_at, updated_at) VALUES (15, 10, 'Produto de exemplo 2', 7, 58.90, 51.90, 'produto-de-exemplo-2', 1, 0, 5, 'ghbwv  we fd
 whny hgwa bh erf w
u jeha E5UY  TR
', 100, 100, 100, 110, 100, 0, '2017-02-21 12:53:20', '2017-02-21 12:53:54');