INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (1, 'autem', '71.806.411/3198-86', 'Aliquam rerum.', 'Sr. Alan Carlos Furtado ltda', 'Velit quaerat possimus asperiores ipsum. Omnis suscipit architecto perferendis et. Est quisquam libero id quidem. Et deserunt amet dolores rerum.
Sequi quia quas expedita atque nemo. Deserunt corporis fugit quia velit sit tenetur mollitia. Et voluptates aliquam omnis deserunt fugiat ea.
Similique dignissimos fuga doloribus debitis. Enim qui pariatur quaerat enim aliquid quaerat. Autem consectetur possimus incidunt eos beatae ut omnis. Quia qui similique autem ad.', 'Facere excepturi quae dignissimos et sint asperiores. Libero excepturi enim in cum delectus. Qui vero numquam natus quis.
Aut id quia non voluptatem dolor quia sit maxime. Veniam voluptas commodi nobis error reprehenderit harum ipsam.
Quo eum consequatur explicabo maxime quae esse. Et debitis laudantium perferendis est qui tempore. Sed et dolore id quibusdam provident. Accusamus incidunt id ipsa quo aut iure.', 'Ut aut sint in voluptatum veritatis. Ducimus possimus minus explicabo rerum nam et. Repellat id repellendus libero fugiat qui. Aliquid non et quia ex eos voluptates.
Maxime iure distinctio laboriosam. Minus commodi sint dolores voluptatem cumque.
Eligendi est quae id rerum autem. Eius sit sed at dolore reprehenderit perspiciatis. Doloremque laudantium in dolorum ut voluptatibus. Nobis fugiat rerum tempora nihil.
Nihil aperiam quis reprehenderit quisquam dolor. Id aut nisi aut.', '9ed0c2644a04e9f031a0d8751e8dcba9.jpg', 'F', 'autem', 2.55, 0, 0, null, '2017-02-21 10:41:04', '2017-02-21 10:41:04');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (17, 'ex', '93.180.257/0517-71', 'Eos quo.', 'Alonso Matias ltda', 'Ipsam explicabo voluptatem eveniet itaque libero fugit optio. Explicabo rerum distinctio sed eveniet. Et voluptatem enim recusandae autem dolorum suscipit minima. Fugit fugiat non harum ut sit minus eos sapiente.
Ut sed mollitia facere ex deserunt. Et vero delectus porro dolore. Occaecati sunt accusantium non ut qui ullam. Rem dicta dolor quidem qui.', 'Excepturi fugiat itaque est consectetur. Qui non saepe at quam. In culpa aut omnis voluptatum maiores.
Soluta voluptatem a qui. Eius minima distinctio exercitationem animi dolor.
Asperiores natus accusantium quis sit aliquid excepturi commodi ducimus. Dolores et sunt ut optio quo. Est excepturi cumque repellendus ab adipisci asperiores voluptatem sed. Tempore nesciunt aliquid veniam suscipit dolor.', 'Laudantium eius natus aut dolorum fuga. Similique id recusandae voluptates voluptate unde nihil. Est consequatur impedit aut in iusto veritatis.
Non laudantium harum dolor. Nostrum dolorum et laudantium voluptatem. Id quo magni dicta accusantium magni fugit ut. Consequatur sint fugit quae placeat sed aliquam.', '82922f03a4ab2054b48e63aeb8804990.jpg', 'J', 'ex', 0.82, 0, 0, null, '2017-02-21 10:41:07', '2017-02-21 10:41:07');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (18, 'qui', '56.214.048/4074-47', 'Excepturi qui.', 'Dr. Elias Corona Filho ltda', 'Perferendis sit delectus nihil ullam officiis eos minima. Facere dolorum rerum omnis maxime quis aut. Nihil molestiae occaecati est aliquid tenetur dolorum.
Dolorum expedita iure similique expedita. Quas quidem dicta aliquam cumque corporis ab. In repellat aut eum voluptatibus dolor assumenda voluptas. Iste eos rerum voluptates eos quidem aut. Rem vero molestiae provident neque in.', 'Beatae aut ut qui aliquam ut qui. Dolore quidem aut harum porro distinctio laudantium ipsa dolores. Sunt molestiae cupiditate error voluptatem veritatis quam sit. Cupiditate itaque repellat odio fugiat nihil. Illo et eos facere tempora in.
Rerum voluptas sit odit et. In saepe voluptate eaque doloremque quia modi molestiae. Facere molestias a nostrum asperiores repudiandae sed. Doloribus unde deleniti accusamus labore pariatur esse.', 'Sunt voluptatem sequi minima aut est reiciendis odit. Perferendis vero nostrum et quia quo ad laboriosam. Et delectus est omnis eos aliquid iste incidunt sit.
Nisi nostrum eum dolores dolorum. Asperiores ut voluptate harum quisquam. Ut est natus beatae et.
Et quis accusamus officia inventore est aut inventore. Nihil at minima suscipit nam veniam sapiente culpa. Rerum atque harum eos eligendi ullam molestias.', 'de4aca4a1d97f8527f92a0b6c5a5661b.jpg', 'J', 'qui', 0.70, 0, 0, null, '2017-02-21 10:41:09', '2017-02-21 10:41:09');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (19, 'dolores', '97.895.474/7559-10', 'Ut sint earum.', 'Isabel Fátima Ferreira Filho ltda', 'Vel aliquam sit a nisi rerum dolores. Quod nesciunt eligendi sed maxime quos assumenda eum. Ea et ut molestias aspernatur explicabo adipisci. Asperiores incidunt vel quasi omnis nihil.
Veritatis atque rem animi dolorem fuga facere velit iure. Expedita non quam est explicabo exercitationem et. Aut fuga aperiam quibusdam sed dolor ipsum autem consequuntur. Sit excepturi totam totam dolorem quia ut repudiandae.
Hic ipsa soluta et corrupti. Sint est qui quas sint. A ullam quia quo ut.', 'Suscipit consequatur a omnis. Labore facilis expedita ut eligendi sit praesentium consequatur. In sequi quis consectetur consequatur rem laudantium. Quo illum qui eius quasi ipsum et. Velit illum velit numquam voluptatibus quia non aut.
Praesentium et id non necessitatibus. Labore sit id rerum dolor nihil facilis possimus. Nemo inventore qui cum veniam veritatis aut. Nisi libero fugit totam fugit.', 'Consectetur commodi reiciendis et maiores ullam quis. Labore corporis officiis quia modi.
Explicabo cupiditate minus nostrum asperiores et. Eos tenetur voluptates est ut deleniti labore. Corporis eum aut eligendi sed.
Optio et laboriosam id quas tempora quia occaecati totam. Ullam perspiciatis provident sed enim sint fugit fugit dolore. Voluptatibus quo voluptate quaerat nesciunt ut dolor.', 'bbb3db26b1ec56bb904dab2ac26e0ffa.jpg', 'J', 'dolores', 3.39, 0, 0, null, '2017-02-21 10:41:12', '2017-02-21 10:41:12');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (20, 'aut', '84.316.605/6054-80', 'Nobis odit.', 'Dr. Felipe Fonseca Bittencourt ltda', 'Ullam minus sapiente iste quam consequatur non sunt. Dolores doloremque quos unde perferendis quis. Sed expedita nihil voluptatum doloremque aut occaecati natus.
Non in rem asperiores nesciunt quam culpa occaecati. Molestiae ducimus provident sed. Eos et in pariatur qui sed rem porro. Voluptatem possimus iste alias animi iusto tenetur neque.', 'Labore aliquam delectus odio labore sed sint. Repudiandae nemo molestiae quis inventore.
Quibusdam earum non aliquid ut. Magnam consectetur voluptatem perspiciatis tenetur. Cum qui dolor eos id.
Et earum pariatur non. Consequatur qui dolor quasi voluptas aliquid iste consectetur.
Sunt quidem reprehenderit totam. Reprehenderit aut sit ea iusto atque dolor dolor. Dolores rerum saepe explicabo. Porro dolore quisquam voluptatem reprehenderit aut eum atque.', 'Placeat soluta corrupti reprehenderit sunt voluptatum. Enim laboriosam pariatur omnis. Aut enim non minima nisi.
Debitis sunt porro molestias nobis. Eum voluptatem quas error voluptatem tempore et mollitia. Sit omnis minus officiis distinctio vitae magnam molestiae. Distinctio alias et sequi.
Commodi ut quo unde voluptatem. Numquam ducimus velit qui quas saepe voluptatibus voluptatum. Deserunt quibusdam sed molestias similique. Adipisci aut quia accusamus totam.', 'dc8ea1f0b6f3b4f3e68f9d4596eb8d10.jpg', 'J', 'aut', 3.30, 0, 0, null, '2017-02-21 10:41:14', '2017-02-21 10:41:14');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (21, 'ad', '95.733.107/9926-86', 'Occaecati doloremque voluptatem.', 'Martinho Franco ltda', 'Ratione aut molestiae laudantium ratione. Qui temporibus non voluptatem ut consectetur et. Reprehenderit minus repellat vel dicta magni unde natus. Maxime deleniti fugit voluptatibus sunt aut eveniet quasi.
Ipsa odit eligendi ullam ipsa. Magnam quia voluptas dolorem sed quidem illum. Aspernatur id consequuntur recusandae modi quas animi. Iusto aspernatur dolores distinctio incidunt quis.', 'Veniam praesentium et non unde ratione enim voluptatem. Tempore molestiae occaecati velit facere voluptas rerum. Porro adipisci eveniet impedit quas velit reiciendis ad praesentium.
Perspiciatis est officiis saepe blanditiis eum fugiat molestias. Harum beatae magnam nostrum repudiandae velit. Doloremque culpa voluptas sint in eum. Enim nemo tempora a nesciunt placeat quis ut pariatur. Dolor magnam nihil quia dolor doloribus.', 'Temporibus ipsa libero id adipisci. Ut porro consequuntur ad voluptatem consequuntur. Excepturi et blanditiis minima. Eum ut eligendi natus voluptas.
Rerum qui inventore eaque dicta. Dicta laudantium et et illum ut eos deserunt quos. Nobis omnis debitis voluptatem dolor.
Eos assumenda et quia officia. Totam optio non nulla dolore nisi quis ea. Et maiores eaque sit velit.', '7818aca0d25d06a65fb495394392b00d.jpg', 'F', 'ad', 1.10, 0, 0, null, '2017-02-21 10:41:16', '2017-02-21 10:41:16');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (22, 'repellendus', '01.250.953/9445-11', 'Et aut ut.', 'Srta. Nádia Delvalle Correia Neto ltda', 'Qui autem atque laborum molestiae. Non autem rem eum eligendi. Occaecati quidem praesentium culpa exercitationem repellendus.
Qui laudantium in numquam et soluta. Laudantium id vel quaerat quisquam harum. Possimus qui qui odit rerum. Eum aliquam fugiat temporibus itaque nisi quae sed.
Molestiae vel et illo mollitia id. Aliquam labore qui eum aut esse in perspiciatis omnis. Qui est ipsum quaerat temporibus.', 'Recusandae culpa esse et. Sapiente sed sunt et nihil dolores sit. Nihil quia repudiandae molestias quam eius ut illo. Ullam libero ipsa ducimus voluptatem sit maiores dolorem. Qui dolores reprehenderit mollitia.
Aspernatur dolores voluptas est voluptatem eius sint eligendi. Quos quia eos fugiat quaerat ut dolorem. Modi a nam aliquam adipisci iure sed ut.
Est ut voluptates non doloremque ut ex quia. Dolorem sed perferendis dolores debitis. Dolor magnam ipsa voluptatum ut quia.', 'Ut architecto voluptatibus cumque voluptatibus. Quo eligendi ut expedita quia ipsam tenetur. Dolor animi qui aut dolore.
Aut deserunt magnam magnam explicabo possimus. Quia quas porro impedit velit. Eius tenetur accusantium in aspernatur voluptatum nihil temporibus ipsa. Placeat similique quia perspiciatis delectus.
Laboriosam et numquam voluptatem. Ipsa officiis tempora tempore rerum et incidunt ut et. Numquam sit dicta ut beatae aspernatur cumque deserunt deleniti.', 'e62df299e29d93d1bb414722150c1495.jpg', 'J', 'repellendus', 2.80, 0, 0, null, '2017-02-21 10:41:18', '2017-02-21 10:41:18');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (23, 'saepe', '00.177.013/2323-69', 'Impedit excepturi maxime.', 'Dr. Gustavo da Silva Sobrinho ltda', 'Et occaecati blanditiis eos libero animi eveniet quidem excepturi. Quidem totam eius blanditiis id ipsum. Autem est sed corporis odit soluta vel dolor. Libero quo totam voluptatem aspernatur commodi quod illum.
Eum nesciunt aut voluptatum maxime commodi vitae cumque esse. Exercitationem quis in nihil magnam. Sunt soluta consequuntur voluptatibus temporibus quia. Mollitia qui nisi similique rem voluptatem iure nobis.', 'At recusandae sit voluptates maiores omnis accusamus. Consectetur exercitationem ipsum sit fugiat. Et itaque iusto error dolores.
Quod nemo quia nulla qui. Accusamus quisquam quas officiis fuga. In commodi earum voluptates et rerum architecto. Ut ex distinctio sint exercitationem iste commodi dolorem.
Asperiores quidem quia laboriosam aut ut. Aut animi optio dicta est. Et soluta hic sint iste.', 'Consectetur mollitia reiciendis quae minima consequatur. Aut eius nobis ut est id ea eos rerum. Voluptates quasi est debitis autem.
Ad hic amet delectus consequatur aut architecto alias omnis. Illum rerum qui consectetur vitae rerum. Consequatur quam nam dolore quam. Beatae beatae soluta sit quod dolor.
Architecto laboriosam provident molestias amet dicta ab. Assumenda officiis corporis facilis voluptatibus. Qui harum ipsam nam modi aut debitis nam.', '559f9af0725bf20c59e929f0c11db70b.jpg', 'J', 'saepe', 0.34, 0, 0, null, '2017-02-21 10:41:21', '2017-02-21 10:41:21');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (24, 'et', '23.937.792/5449-87', 'Sed doloribus.', 'Vitória Maldonado Benites Filho ltda', 'Voluptatem saepe autem quas numquam. Ut ratione aut ipsum. Assumenda ratione voluptate saepe tempore nisi sed.
Cupiditate omnis ipsa aut aut. Dolorem ut vero et quod ratione qui qui. Autem saepe incidunt magni nihil. Accusantium aut placeat sed quia dolores enim.
Voluptas tempora quas non dicta necessitatibus non quo itaque. A atque non enim qui eius. Nesciunt nobis sit quas quasi dolores enim.', 'Nihil perspiciatis perspiciatis vitae quos commodi similique. Maxime eum accusamus fugit eaque. Repellendus doloribus dolores molestiae repellendus. Sunt dolorem ut minima qui architecto sunt voluptatibus.
Provident voluptatem excepturi veritatis reiciendis. Explicabo dolores iure eos minus eligendi recusandae ea sapiente. Et blanditiis et quis aut nemo quia quia corporis. Repellat nemo est sint minus. Id sequi voluptate architecto non.', 'Id numquam dolores repellat dolor deleniti blanditiis quis. Hic rem occaecati non dolores autem ab non. Quas ut ut et.
Ipsum saepe qui et qui quos. Itaque veritatis sed ipsam voluptatibus. Voluptatum sed ut dolor ad ut numquam. Dolores et commodi in.
Nisi et earum eos nemo voluptate necessitatibus officia. Ut tempora quo numquam inventore. Fuga hic error temporibus. Mollitia similique ut ab et.', '2559a806d958df42654dabd726551e02.jpg', 'F', 'et', 3.69, 0, 0, null, '2017-02-21 10:41:23', '2017-02-21 10:41:23');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (25, 'ea', '49.036.459/9488-32', 'Et est voluptatem.', 'Madalena Regina Colaço Sobrinho ltda', 'Vel ut quas enim unde. Ut error reiciendis nemo ut molestiae aut ratione eius. Dolor unde natus sed.
Id reprehenderit nam repellendus voluptatibus ut vero iure deserunt. Similique aliquid quasi totam quasi eveniet. Tempora ea quasi quasi exercitationem. Velit cum laboriosam delectus ut.
Et in similique ut a eos occaecati ea. Et commodi id numquam rem. Inventore odio similique voluptatem iste rerum deleniti animi. Architecto facere voluptatem maxime sit impedit ex.', 'Quia dicta minus nemo ut error est nesciunt. Incidunt voluptates et aut. Quia possimus debitis incidunt et et. Architecto voluptatibus deleniti totam atque nemo id qui.
A dolorum ut id velit est praesentium. Eaque voluptatibus praesentium atque commodi rem soluta. Eaque quibusdam quis distinctio et ab. Rerum aspernatur quaerat repudiandae nobis.
Quasi debitis aut omnis ab rerum reprehenderit. Deserunt debitis voluptas dolor beatae.', 'Cum minus et esse mollitia ut at. Sed autem nihil assumenda itaque alias assumenda doloremque. Quae eaque temporibus repudiandae eligendi debitis.
Voluptas sit voluptatem nulla in voluptatem mollitia. Et et sed velit aut corporis dolores quod. Ullam qui sint sequi consequatur.', '9a7699e7ccf88d25931c5fdfa8aabded.jpg', 'F', 'ea', 3.16, 0, 0, null, '2017-02-21 10:41:29', '2017-02-21 10:41:29');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (26, 'deserunt', '39.548.585/0866-50', 'Rerum eveniet.', 'Thales Thiago Sales ltda', 'Nihil magnam ut occaecati consequuntur. Iure totam aut ut soluta alias expedita suscipit. Consectetur perferendis eos ab quis voluptas voluptate.
Omnis delectus alias neque rerum aut debitis ut. Et adipisci esse ut veritatis qui similique. Vero molestias tempora et quia et quo sed quos. Natus dolorem beatae nesciunt aliquam quis dolorem.
Velit est aut numquam voluptas eius ut. Libero delectus et veniam accusamus minima est qui. Mollitia eos tempore similique in recusandae et quia.', 'Eos quae facere nostrum officia reiciendis blanditiis. Ut numquam libero aperiam aperiam aperiam quisquam qui. Quam aut dignissimos doloremque pariatur hic. Fugiat facere voluptas reprehenderit et.
Veritatis quae deleniti neque magni. Rerum voluptatem quia qui consequatur nihil similique voluptates. Id in incidunt repudiandae vel voluptatem quo.
Qui odit perferendis aut ut dolorem excepturi vel molestiae. Veritatis ex ex fugit.', 'Pariatur sit quae omnis officia. Omnis beatae voluptatem animi qui maiores illum. Praesentium quibusdam est at et. Et atque repellendus id soluta.
Deleniti animi soluta omnis quaerat deleniti ut est. Aut maiores ullam officiis sed tempora est. Non est eveniet et repellat. Eveniet voluptatem harum id ut cupiditate quo.
Totam fuga cum blanditiis consequatur ullam optio quisquam. Sed veritatis animi eveniet et. Et et rerum aut esse.', '9a60df307a413fcec42771bf213ef78c.jpg', 'J', 'deserunt', 4.78, 0, 0, null, '2017-02-21 10:41:31', '2017-02-21 10:41:31');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (27, 'nostrum', '78.543.300/2145-98', 'Et consequatur sit.', 'Sr. Agostinho Cortês ltda', 'Rem perspiciatis nesciunt sunt laborum commodi harum. Veniam odit fuga eum suscipit rerum et minus. Omnis quia dolores placeat mollitia autem et. Voluptatibus totam sit consequuntur sint omnis dignissimos dolore. Exercitationem in neque aut deserunt id et natus.
Aspernatur tenetur sed et enim. Qui saepe omnis quia saepe. Excepturi est quibusdam quasi et possimus dolores voluptatem. Dolor mollitia illo aut quod sed aut. Illum qui ut qui quidem sapiente.', 'Voluptatem quibusdam cumque tenetur odio recusandae laborum nesciunt. Voluptates tempora et voluptatem. Nesciunt sed non explicabo facilis rerum itaque enim ullam. Vitae facilis possimus at laudantium debitis ea.
Sed at laboriosam placeat. Atque repellat nostrum impedit deleniti quisquam similique fugit. Dolores debitis ut et laboriosam. Temporibus dolorem pariatur qui harum nam fugit ut alias.', 'Veniam porro consectetur quis ab omnis quaerat illo. Quasi facilis rerum occaecati harum voluptas commodi. Ipsam voluptatem corrupti culpa nostrum. Unde eius consectetur vel.
Sed laudantium inventore placeat est. Vel nihil veniam minima ipsa.
Quos cupiditate maxime rerum quo aut. Quis est eius voluptates.
Est repudiandae sit harum. Temporibus quia iusto dignissimos nemo. Porro veniam dolor saepe ut sint. Corrupti beatae incidunt id.', '346eeb30659b9bd54c24795351375e76.jpg', 'J', 'nostrum', 4.08, 0, 0, null, '2017-02-21 10:41:33', '2017-02-21 10:41:33');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (28, 'explicabo', '87.147.318/7574-09', 'Asperiores sequi.', 'Luzia Santiago ltda', 'Qui minima ut tenetur quis. Aspernatur quam eos inventore quia alias cumque consequatur. Veritatis sit ea unde placeat quibusdam ut a. Ullam quo non quasi vel distinctio.
Sint fugit in nostrum est aut sed atque. Voluptas nihil ipsa exercitationem harum.
Consectetur eligendi voluptatibus illo voluptas non a rerum. Eius sit provident animi et molestiae velit. Doloremque earum error est enim fuga nostrum.', 'Non iusto maiores inventore sit ut officiis. Molestiae optio iusto tenetur doloribus quod iste.
Distinctio sapiente eveniet ab nobis eos non culpa. Eligendi dolor sed ea eos enim esse numquam. Placeat officiis sequi cupiditate recusandae. Qui velit aut doloremque sequi amet.
Sit accusantium rerum recusandae beatae aliquam. Asperiores quia rerum nihil. Hic ratione consequatur voluptatem.', 'Explicabo velit nemo atque sapiente qui. Reprehenderit qui fugit veniam suscipit ex vero ut. Deserunt nihil ipsa et dolores necessitatibus omnis. Eos esse eos qui eveniet.
Animi minima neque ex asperiores adipisci. Saepe ipsa adipisci aut aut. At eos est et. Nihil ipsa atque et mollitia quos aut.
Qui laboriosam consequatur consequuntur ab. Deleniti nulla illo sit. Nemo animi atque maiores iusto. Eaque ducimus dolorem animi voluptas doloremque cum est modi. Unde sunt et ipsum.', '803ecb0152fa0a32fbcc505baee3658a.jpg', 'F', 'explicabo', 3.33, 0, 0, null, '2017-02-21 10:41:36', '2017-02-21 10:41:36');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (29, 'quo', '71.063.587/3973-44', 'Nesciunt quibusdam.', 'Hugo Colaço Jimenes Sobrinho ltda', 'Quisquam maiores rerum dignissimos ducimus. Laborum aspernatur rem minus consequatur. Aut magni ut ea quas non a commodi.
Voluptatem harum culpa ex rem velit quisquam consectetur. Sunt nam natus fuga quia expedita. Odio dicta et sunt qui consequuntur beatae. Voluptatem officia sit voluptatum.
Totam autem accusantium consectetur at. Enim et eaque animi et qui et. Placeat sit aut expedita quas voluptas.', 'Totam maxime dolor exercitationem dolorem aliquid voluptatem. Dolores cupiditate qui vero perspiciatis et. A veritatis saepe omnis. Expedita dolorem quo id expedita laboriosam quis quibusdam.
Velit vero voluptatem ad consequatur soluta tempore quas. Quibusdam mollitia fugit aperiam aut nihil. Veritatis vitae impedit alias harum nihil repellendus.', 'Alias iste ipsam consequatur. Excepturi unde explicabo harum magnam. Voluptatem eum laboriosam recusandae id tenetur hic error.
Quia similique corporis sed fugit sit ad qui. Eius blanditiis quia impedit optio fuga nisi ut perferendis. Dolor accusantium quod sint aut.
Animi animi et est maxime dolore id adipisci. Voluptatem sed at cupiditate sit. Rerum in ratione laudantium cum. Perspiciatis at delectus fugiat ipsam. Nesciunt numquam voluptatem quia deserunt.', '2b53e8b896df53e379b6a40381934392.jpg', 'J', 'quo', 4.42, 0, 0, null, '2017-02-21 10:41:41', '2017-02-21 10:41:41');
INSERT INTO popmartin.stores (salesman_id, name, cnpj, fantasy_name, social_name, about, exchange_policy, freight_policy, logo_file, type_salesman, slug, rate, active, blocked, deleted_at, created_at, updated_at) VALUES (30, 'Minha Loja', '', '', '', 'sdasd asd', 'as das wefq qw', 'erty5hwg awe', 'L15V30U1.png', 'F', 'minha-loja', null, 0, 0, null, '2017-02-21 12:15:00', '2017-02-21 12:47:04');